{
  "train-data-paths": ["/data/pile/pile_0.87_deduped_text_document"],
  "valid-data-paths": ["/data/pile/pile_0.87_deduped_text_document"],
  "test-data-paths": ["/data/pile/pile_0.87_deduped_text_document"],

  "tokenizer-type": "HFTokenizer",
  "vocab-file": "/data/tokenizers/20B_tokenizer.json",

  "save": "/data/chk/min-pythia",
  "load": "/data/chk/min-pythia",
  "checkpoint_validation_with_forward_pass": False
}
