{
  "train-data-paths": ["/home/mchorse/data/openwebtext2/openwebtext2_text_document"],
  "valid-data-paths": ["/home/mchorse/data/openwebtext2/openwebtext2_text_document"],
  "test-data-paths": ["/home/mchorse/data/openwebtext2/openwebtext2_text_document"],

  "tokenizer-type": "HFTokenizer",
  "vocab-file": "/home/mchorse/data/tokenizers/20B_tokenizer.json",

  "save": "/home/mchorse/chk/",
  "load": "/home/mchorse/chk/",
  "checkpoint_validation_with_forward_pass": False,

  "train-iters": 7680,
  "lr-decay-iters": 7680,
  "eval-interval": 7680,
  "warmup": 0.18
}
