{
  # parallelism settings
  "pipe-parallel-size": 0,
  "model-parallel-size": 1,

  "zero_optimization": {
    "stage": 0,
    "allgather_partitions": true,
    "allgather_bucket_size": 50000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 50000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },

  # batch size (set for 2 GPUs)
  "train_micro_batch_size_per_gpu": 32,
  "gradient_accumulation_size": 16,

  # Number of dataloader workers
  "num_workers": 4,
}
